### ISSUE TITLE
k8s follow-up - Uniformise core config keys

### ISSUE THREAD

**Issue by davidferlay** [launchrctl/launchr#110]
## Context

- Followup of [k8s support](https://github.com/launchrctl/launchr/pull/99) which introduces `container.runtime: kubernetes`

## Observed

- In config.yaml, 
   - `actions_naming` config key is at yaml root
   - `runtime: kubernetes` is bellow `container` key

```
launchrctl:
  actions_naming:
    - search: ".roles."
      replace: "."
    - search: "_"
      replace: "-"
container:
  runtime: kubernetes
```

## Expected

- Move actions_naming config key to yaml root instead of launchrctl.actions_naming for consistency
