### ISSUE TITLE
Introduce meta actions

### ISSUE THREAD

**Issue by davidferlay** [launchrctl/launchr#26]
## Observed

User may need to often execute the same suite of commands
Yet there is no way to execute multiple actions using only 1 single command

For instance, For each deploy, after having done some devlopments+bumped, user currently needs to run 4 actions
```
plasmactl compose --skip-not-versioned --conflicts-verbosity
plasmactl platform:compare-artifacts
plasmactl platform:components-propagate dev file.diff
```

Gradle has a way to do that "meta action": The common pattern there is to have a task that depends on tasks. One task that has ONLY dependencies will be a "meta" task

## Expected

Would be great to have a way to define meta actions, where one command would run multiple actions
- This should work for both commands brought by native plugins + commands brought by actions
- Maybe meta action should be defined with a different kind of action.yaml
```
action:
  kind: Meta
  title: Build
  description: Handles every actions related to building artifact to be deployed
  actions: 
    - compose --skip-not-versioned --conflicts-verbosity
    - platform:compare-artifacts
    - platform:components-propagate dev file.diff
```
- **Or** maybe instead of creating a new kind of action, it could be handled solely by dependencies, like 
   - action `platform:components-propagate` has an attribute that says it need to run `platform:compare-artifacts` before running itself
   - and action `platform:compare-artifacts dev file.diff` has an attribute that says it need to run `compose --skip-not-versioned --conflicts-verbosity` before running itself
   - but in this case need ability to run all actions with expected args and options

In any case, maybe this functionality should be brought by a launchrctl plugin, to keep functionality separate from core and keep it simple

- **Or** maybe instead of adding this to launchrctl, we could simply use a Makefile (or something similar)
