### ISSUE TITLE
Allow enum options 

### ISSUE THREAD

**Issue by iberdinsky-skilld** [launchrctl/launchr#57]
https://json-schema.org/understanding-json-schema/reference/enum

Currently enum not allowed on backend side

```
action:
  options:
    - name: applications
      type: array
      items:
        type: string
        enum:
          - 'foo'
          - 'bar'
          - 'fuzz'
          - 'qux'
```
