### ISSUE TITLE
Allow(Disquss) objects support.  

### ISSUE THREAD

**Issue by iberdinsky-skilld** [launchrctl/launchr#58]
In case of grouped options object support for options may be required. It will also give ability to group them on ui side

```
action:
  title: Set up colors
  options:
    - name: colors
      type: object
      properties:
        - name: Brand color
          type: string
        - name: Secondary color
          type: string

```
