### ISSUE TITLE
Impossible to set up default value for arrays

### ISSUE THREAD

**Issue by iberdinsky-skilld** [launchrctl/launchr#59]
Default value cannot be setted for array

Next not works:

```
action:
  options:
    - name: applications
      type: array
      default: ['foo', 'bar', 'fuzz', 'qux']
```

output:

```
        panic: interface conversion: interface {} is nil, not string
```
