### ISSUE TITLE
Arguments are not explained in action --help

### ISSUE THREAD

**Issue by davidferlay** [launchrctl/launchr#6]
## Context

- Consider action defined as such: 
```
➜  cat platform/actions/compare-artifact/action.yaml 
action:
  title: Compare artifact
  description: Get expected artifact to compare current one and generate diff file
  arguments:
    - name: username
      title: Username
      description: The username to get comparison artifact with
    - name: password
      title: Username
      description: The password to get comparison artifact with
  options:
    - name: override
      title: Overriden comparison reference (branch or tag name)
  image: platform-actions-compare-artifact:latest
  build:
    context: ./
    args:
      USER_ID: {{.current_uid }}
      GROUP_ID: {{.current_gid}}
    tags:
      - platform-actions-compare-artifact:latest
      - platform-actions-compare-artifact:1.0.0
  command:
    - sh
    - /action/x.sh
    - "{{.username}}"
    - "{{.password}}"
    - "{{.override}}"
```

## Observed

- We can see that `options` are described in `--help` (see `--override`) but arguments are not -`username`, `password`)
```
✗ launchr platform:compare-artifact --help
Usage:
  plasmactl platform:compare-artifact username password [flags]

Flags:
  -h, --help                              help for platform:compare-artifact
      --overriden_comparison_ref string   Overriden comparison reference (branch or tag name)

Global Flags:
      --keyring-passphrase string   Passphrase for keyring encryption/decryption
  -q, --quiet                       disable stdOut
  -v, --verbose count               log verbosity level, use -vvv DEBUG, -vv WARN, -v INFO
```

## Expected

- Both options and arguments should be listed in --help of actions
