### ISSUE TITLE
User uid gid works when passed to Dockerfile using ARG but not ENV

### ISSUE THREAD

**Issue by davidferlay** [launchrctl/launchr#7]
## Context

- Following https://github.com/launchrctl/launchr/commit/3ba937c571c10a700d533d27faa506c91c70dd1e

## Observed

- User uid gid works when passed to Dockerfile using ARG but not ENV : 
- So this is working : 

action.yaml: 
```
action:
  title: Compare artifact
  description: Get expected artifact to compare current one and generate diff file
  arguments:
    - name: username
      title: Username
      description: The username to get comparison artifact with
    - name: password
      title: Username
      description: The password to get comparison artifact with
  options:
    - name: override
      title: Overriden comparison reference (branch or tag name)
  image: platform-actions-compare-artifact:latest
  build:
    context: ./
    args:
      USER_ID: {{.current_uid }}
      GROUP_ID: {{.current_gid}}
    tags:
      - platform-actions-compare-artifact:latest
      - platform-actions-compare-artifact:1.0.0
  command:
    - sh
    - /action/x.sh
    - "{{.username}}"
    - "{{.password}}"
    - "{{.override}}"
```
Dockerfile:
```
FROM alpine:3.18
WORKDIR /host
ARG USER_ID
ARG GROUP_ID
RUN echo ${USER_ID}
RUN echo ${GROUP_ID}
RUN adduser -D -u $USER_ID -g $GROUP_ID plasma || true
USER plasma
```
- But this is not working : 

action.yaml: 
```
action:
  title: Compare artifact
  description: Get expected artifact to compare current one and generate diff file
  arguments:
    - name: username
      title: Username
      description: The username to get comparison artifact with
    - name: password
      title: Username
      description: The password to get comparison artifact with
  options:
    - name: override
      title: Overriden comparison reference (branch or tag name)
  image: platform-actions-compare-artifact:latest
  build:
    context: ./
    env:
      USER_ID: {{.current_uid }}
      GROUP_ID: {{.current_gid}}
    tags:
      - platform-actions-compare-artifact:latest
      - platform-actions-compare-artifact:1.0.0
  command:
    - sh
    - /action/x.sh
    - "{{.username}}"
    - "{{.password}}"
    - "{{.override}}"
```
Dockerfile:
```
FROM alpine:3.18
WORKDIR /host
RUN echo ${USER_ID}
RUN echo ${GROUP_ID}
RUN adduser -D -u $USER_ID -g $GROUP_ID plasma || true
USER plasma
```

## Expected

- `{{.current_uid }}` and `{{.current_gid}}` defined in action.yaml should be able to be passed to Dockerfile
